#!/bin/sh

RED=31
GREEN=32
YELLOW=33
BLUE=34
PASSED=true

log() {
	TRIMMED=$(echo "$2" | xargs)

	if [ ! -z "$TRIMMED" ]; then
		echo "\033[0;$1m[pre-commit] ### $2\033[0m"
	fi
}

info() {
	log "$BLUE" "$1"
}

success() {
	log "$GREEN" "$1"
}

danger() {
	log "$RED" "$1"
}

warning() {
	log "$YELLOW" "$1"
}

check() {
	if [ "$?" = 0 ]; then
		success "$1\n"
	else
		danger "$2\n"
		PASSED=false
	fi
}

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep "[jt]s$")

if [ "$STAGED_FILES" = "" ]; then
	exit 0
fi

# typescript
info "Running type-checks"
npx tsc -p tsconfig.json --noEmit
check "Completed type-checks" "Type-checks failed"

# prettier
info "Running prettier"
npx prettier . --write 2>&1 >/dev/null
check "Completed prettifying" "Prettifying failed"

# eslint
info "Linting"

for FILE in $STAGED_FILES; do
	npx eslint "$FILE"
	check "" "Linting failed: $FILE"
done

success "Completed linting\n"

# result
if ! $PASSED; then
	danger "Commit failed\n"
	exit 1
else
	info "Commit succeeded\n"
fi
